//This class was created on 2018.11.23 by Jaco van Stryp
package frontend;

import backend.dbLocationManager;
import java.io.File;
import java.util.Scanner;

/**
 *
 * @author Jaco van Stryp
 */
public class MainAllBookRecords extends javax.swing.JFrame {

    dbLocationManager cm = new dbLocationManager();

    /**
     * Creates new form MainUserInterface
     */
    public MainAllBookRecords() {
        initComponents();
        this.loadAllBookData();
               mainReport.setCaretPosition(0);

    }
    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVote8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainReport = new javax.swing.JTextArea();
        btnVote9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eduplex Book Management System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 8, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, -1, -1));

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Eduplex EVS v5 Small.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eduplex Book Management System");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 67, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 477, 8, 24));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Report");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        btnVote8.setBackground(new java.awt.Color(255, 89, 33));
        btnVote8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote8.setForeground(new java.awt.Color(255, 255, 255));
        btnVote8.setText("Refresh");
        btnVote8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 510, 40));

        mainReport.setBackground(new java.awt.Color(34, 34, 78));
        mainReport.setColumns(20);
        mainReport.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        mainReport.setForeground(new java.awt.Color(255, 255, 255));
        mainReport.setRows(5);
        jScrollPane1.setViewportView(mainReport);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1100, 410));

        btnVote9.setBackground(new java.awt.Color(255, 89, 33));
        btnVote9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote9.setForeground(new java.awt.Color(255, 255, 255));
        btnVote9.setText("Main Menu");
        btnVote9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 510, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //Code will log the user out and then close the program

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed

    }//GEN-LAST:event_jLabel15MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //This is used so the user can drag the window around without it having an frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MouseReleased

    private void btnVote8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote8ActionPerformed
       this.loadAllBookData();
       mainReport.setCaretPosition(0);

    }//GEN-LAST:event_btnVote8ActionPerformed

    private void btnVote9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote9ActionPerformed
        new MainUserInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVote9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAllBookRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAllBookRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAllBookRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAllBookRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAllBookRecords().setVisible(true);
            }
        });
    }

    public void loadAllBookData() {
        String dbLoc = cm.getDatabaseLocation();
        try {
            String lang = "Subjects";
            String grade = "0";
            mainReport.setText("All Book Records\n\n\nEnglish\n\n\n");
           ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 1\n");
         
                
            
            grade = "1";
            String location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
            File folder = new File(location);
            File[] listOfFiles = folder.listFiles();
            String finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            /////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 3\n");
           
            grade = "3";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 2\n");
           
            grade = "2";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
   ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 3\n");
           
            grade = "3";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 4\n");
           
            grade = "4";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 5\n");
           
            grade = "5";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 6\n");
           
            grade = "6";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 7\n");
           
            grade = "7";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 7\n");
           
            grade = "7";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 8\n");
           
            grade = "8";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 9\n");
           
            grade = "9";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 10\n");
           
            grade = "10";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 11\n");
           
            grade = "11";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 12\n");
           
            grade = "12";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nTeachers\n");
           
            grade = "Teacher";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            
            ///////////////////////////////////////////////
            
            
           lang = "Vakke";
         
            mainReport.append("\n\n\nAfrikaans\n\n\n");
           ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 1\n");
         
                
            
            grade = "1";
         location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
            folder = new File(location);
            listOfFiles = folder.listFiles();
            finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            /////////////////////////////////////////////// ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 3\n");
           
            grade = "3";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 2\n");
           
            grade = "2";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
   ///////////////////////////////////////////////////////////////////
            mainReport.append("\nGrade 3\n");
           
            grade = "3";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 4\n");
           
            grade = "4";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 5\n");
           
            grade = "5";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 6\n");
           
            grade = "6";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 7\n");
           
            grade = "7";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 7\n");
           
            grade = "7";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 8\n");
           
            grade = "8";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 9\n");
           
            grade = "9";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 10\n");
           
            grade = "10";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 11\n");
           
            grade = "11";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nGrade 12\n");
           
            grade = "12";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
            ///////////////////////////////////////////////
             mainReport.append("\nTeachers\n");
           
            grade = "Teacher";
             location = dbLoc + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade;//Loads Folder
             folder = new File(location);
             listOfFiles = folder.listFiles();
             finalLocation = "";
            for (int i = 0; i < listOfFiles.length; i++) {
                if (listOfFiles[i].isFile()) {

                    Scanner scFile = new Scanner(new File(listOfFiles[i].getAbsoluteFile() + ""));
                    String prev = "";
                    while (scFile.hasNextLine()) {
                        String cur = listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3);
                        if (prev.equalsIgnoreCase(cur)) {
                            prev = cur;
                        } else {
                            mainReport.append("\n\nSubject - " + listOfFiles[i].getName().substring(0, listOfFiles[i].getName().length() - 3) + "\n");
                            prev = cur;
                        }
                        mainReport.append("\nBook - " + scFile.nextLine().replaceAll("#", "\nBook Code - ") + "\n");
                    }
                    mainReport.append("\n---------------------------------");
                    scFile.close();

                }
            }
        } catch (Exception ex) {

        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVote8;
    private javax.swing.JButton btnVote9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainReport;
    // End of variables declaration//GEN-END:variables
}
