//This class was created on 2018.11.23 by Jaco van Stryp
package frontend;

import backend.dbLocationManager;
import backend.genCodes;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Jaco van Stryp
 */
public class MainCreateBook extends javax.swing.JFrame {

    /**
     * Creates new form MainUserInterface
     */
    dbLocationManager cm = new dbLocationManager();

    public MainCreateBook() {
        initComponents();
    }
    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVote2 = new javax.swing.JButton();
        tfSubject = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        btnVote3 = new javax.swing.JButton();
        btnVote4 = new javax.swing.JButton();
        btnVote5 = new javax.swing.JButton();
        btnVote6 = new javax.swing.JButton();
        btnA = new javax.swing.JCheckBox();
        btnE = new javax.swing.JCheckBox();
        jLabel59 = new javax.swing.JLabel();
        comGrade = new javax.swing.JComboBox<>();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eduplex Book Management System");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(8, 8, 94));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eduplex Book Management System");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Eduplex EVS v5 Small.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 67, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 477, 8, 24));

        btnVote2.setBackground(new java.awt.Color(255, 89, 33));
        btnVote2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote2.setForeground(new java.awt.Color(255, 255, 255));
        btnVote2.setText("Display All Books");
        btnVote2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 190, 40));

        tfSubject.setBackground(new java.awt.Color(34, 34, 78));
        tfSubject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfSubject.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 860, 40));

        jLabel55.setBackground(new java.awt.Color(255, 255, 255));
        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Book Subject:");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, 40));

        tfName.setBackground(new java.awt.Color(34, 34, 78));
        tfName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 860, 40));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Student Language :");
        jPanel1.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 40));

        btnVote3.setBackground(new java.awt.Color(255, 89, 33));
        btnVote3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote3.setForeground(new java.awt.Color(255, 255, 255));
        btnVote3.setText("Create Book");
        btnVote3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 170, 40));

        btnVote4.setBackground(new java.awt.Color(255, 89, 33));
        btnVote4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote4.setForeground(new java.awt.Color(255, 255, 255));
        btnVote4.setText("Remove Book");
        btnVote4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 170, 40));

        btnVote5.setBackground(new java.awt.Color(255, 89, 33));
        btnVote5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote5.setForeground(new java.awt.Color(255, 255, 255));
        btnVote5.setText("Display Outstanding Books");
        btnVote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 280, 40));

        btnVote6.setBackground(new java.awt.Color(255, 89, 33));
        btnVote6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVote6.setForeground(new java.awt.Color(255, 255, 255));
        btnVote6.setText("Main Menu");
        btnVote6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnVote6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 190, 40));

        btnA.setBackground(new java.awt.Color(255, 255, 255));
        btnA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnA.setForeground(new java.awt.Color(255, 255, 255));
        btnA.setText("Afrikaans");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        jPanel1.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 160, 50));

        btnE.setBackground(new java.awt.Color(255, 255, 255));
        btnE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnE.setForeground(new java.awt.Color(255, 255, 255));
        btnE.setText("English");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        jPanel1.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 160, 50));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Please Fill In All Of The Information Acording To The Book's Language");
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 1020, 40));

        comGrade.setBackground(new java.awt.Color(37, 37, 103));
        comGrade.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comGrade.setForeground(new java.awt.Color(255, 255, 255));
        comGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "Teacher" }));
        jPanel1.add(comGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 860, 60));

        jLabel57.setBackground(new java.awt.Color(255, 255, 255));
        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Book Name :");
        jPanel1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 40));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Book Grade :");
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVote2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote2ActionPerformed
        
        new MainAllBookRecords().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVote2ActionPerformed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MouseReleased

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        //This is used so the user can drag the window around without it having an frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed

    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //Code will log the user out and then close the program

        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnVote3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote3ActionPerformed
        String sub = tfSubject.getText();
        String name = tfName.getText();
        String grade = comGrade.getSelectedItem().toString();
        boolean active = true;
        String lang = "";
        if (btnA.isSelected()) {
            lang = "Vakke";
        } else if (btnE.isSelected()) {
            lang = "Subjects";
        } else {
            active = false;
        }
        sub = sub.trim();
        name = name.trim();
        if (sub.equals("") || name.equalsIgnoreCase("") || active == false) {
            JOptionPane.showMessageDialog(null, "Fill In All Fields", "Please Make Sure All Fields Are Filled In", JOptionPane.ERROR_MESSAGE);
        } else { //TODO
            PrintWriter printer = null;
            try {
                genCodes gc = new genCodes();
                String gCode = gc.genBook();
                System.out.println(grade);
                if (btnE.isSelected() == true && btnA.isSelected() == true) {
                    printer = new PrintWriter(new FileWriter(cm.getDatabaseLocation() + "\\Book_Management_Admin\\Books\\" + "Subjects" + "\\" + "Grade_" + grade + "\\" + sub + ".db", true));
                    printer.println(name + "#" + gCode);
                    PrintWriter printerS = new PrintWriter(new FileWriter(cm.getDatabaseLocation() + "\\Book_Management_Admin\\Books\\" + "Vakke" + "\\" + "Grade_" + grade + "\\" + sub + ".db", true));
                    printerS.println(name + "#" + gCode);
                     printer.close();
                     printerS.close();
                } else {

                    printer = new PrintWriter(new FileWriter(cm.getDatabaseLocation() + "\\Book_Management_Admin\\Books\\" + lang + "\\" + "Grade_" + grade + "\\" + sub + ".db", true));
                    printer.println(name + "#" + gCode);
                     printer.close();
                }
               
                tfSubject.setText("");
                tfName.setText("");
                btnA.setSelected(false);
                btnE.setSelected(false);
                JOptionPane.showMessageDialog(null, "Book Saved Successfuly!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                cm.createAllSubFolders();
                JOptionPane.showMessageDialog(null, "Something Went Wrong\n\nWe Attempted To Fix The Problem\n\nPlease Try Again\n\nIf This Problem Repeats Itself, Please Reinstall The Main Database Directory", "Warning", JOptionPane.WARNING_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnVote3ActionPerformed

    private void btnVote4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVote4ActionPerformed

    private void btnVote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVote5ActionPerformed

    private void btnVote6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote6ActionPerformed
       new MainUserInterface().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVote6ActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed

    }//GEN-LAST:event_btnAActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed

    }//GEN-LAST:event_btnEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCreateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCreateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCreateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCreateBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCreateBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnA;
    private javax.swing.JCheckBox btnE;
    private javax.swing.JButton btnVote2;
    private javax.swing.JButton btnVote3;
    private javax.swing.JButton btnVote4;
    private javax.swing.JButton btnVote5;
    private javax.swing.JButton btnVote6;
    private javax.swing.JComboBox<String> comGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSubject;
    // End of variables declaration//GEN-END:variables
}
